<<<<<<< HEAD
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
=======

// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
>>>>>>> d282a3810cbf7cbc9068d4230e349a3be90eecd7

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
<<<<<<< HEAD
  datasource: {
    url: process.env["DATABASE_URL"],
=======
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
>>>>>>> d282a3810cbf7cbc9068d4230e349a3be90eecd7
  },
});
